name: CI
on:
  pull_request:
  push:
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - java: 11
          - java: 14
          - java: 24
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up JVM with Coursier
      uses: coursier/setup-action@v1
      with:
        jvm: zulu:${{ matrix.java }}
    - name: Scalafmt
      run: sbt -v scalafmtCheckAll
    - name: Build and Test
      run: sbt -v -Dfile.encoding=UTF-8 +test
